apiVersion: v1
kind: Service
metadata:
  name: messageservice
spec:
  selector:
    app: messageservice
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice
spec:
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
      - name: messageservice
        image: jingjunlongsap/messageservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080