apiVersion: v1
kind: Service
metadata:
   name: message
   labels:
      app: message
spec:
   type: NodePort
   ports:
   -  port: 8080
      name: http
   selector:
      app: message
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
   name: message #名称
   labels:
      app: message #标注 
spec:
   replicas: 2 #运行容器的副本数，修改这里可以快速修改分布式节点数量
   selector:
      matchLabels:
         app: message
   template:
      metadata:
         labels:
            app: message
      spec:
         containers: #docker容器的配置
         -  name: message
            image: jingjunlongsap/messageservice:latest # pull镜像的地址 ip:prot/dir/images:tag
            imagePullPolicy: Always #pull镜像时机，
            ports:
            -  containerPort: 8080 #容器对外开放端口